---
title: "Final Project"
author: "Brendan Gillespy and Justin Thoms"
date: "5/11/2020"
output: 
  html_document:
    code_folding: hide
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE}
library(tidyverse)
```


```{r tables, message=FALSE}
attendance2013 <- read_csv("college-football-statistics/cfbstats-com-2013-1-5-20/game-statistics.csv")
teamGameStats2013 <- read_csv("college-football-statistics/cfbstats-com-2013-1-5-20/team-game-statistics.csv")
rushing2013 <- read_csv("college-football-statistics/cfbstats-com-2013-1-5-20/rush.csv")
passing2013 <- read_csv("college-football-statistics/cfbstats-com-2013-1-5-20/pass.csv")
teams2013 <- read_csv("college-football-statistics/cfbstats-com-2013-1-5-20/team.csv")
games2013 <- read_csv("college-football-statistics/cfbstats-com-2013-1-5-20/game.csv")
confrence2013 <- read_csv("college-football-statistics/cfbstats-com-2013-1-5-20/conference.csv")
#Todo: Import all tables, and concat the tables with rbind()
```   

```{r organizeData}
findPoints <- function(gameCode, teamCode){
  opponentPoints <- teamGameStats2013 %>%
    filter(`Game Code` == gameCode & `Team Code` != teamCode) %>%
    select(Points)
  as.double(opponentPoints[1,1])
}

for(i in 1:nrow(teamGameStats2013)){
  teamGameStats2013[i,69] = findPoints(as.character(teamGameStats2013[i,2]), as.double(teamGameStats2013[i,1]))
}

names(teamGameStats2013)[69] <- "opponentPoints"

teamGameStats2013 <- teamGameStats2013 %>%
  mutate(win=opponentPoints<Points)

seasonWins2013 <- teamGameStats2013 %>%
  filter(win == TRUE) %>%
  group_by(`Team Code`) %>%
  summarize(Wins=n())
```

```{r graph}
# See points scored per game per each number of total yardage
teamGameStats2013 %>%
  ggplot((aes(x=(`Rush Yard`+`Pass Yard`+`Kickoff Ret Yard`+`Punt Ret Yard`+`Misc Ret Yard`+`Int Ret Yard`+`Fum Ret Yard`), y=Points))) +
  geom_point() +
  geom_smooth(method=lm) +
  labs(x="Total Yards",
       y="Points Scored",
       title = "Points Scored per Yard by Game")

# See the distribution of rushing yards per attempt by several top football schools
rushing2013 %>%
  filter(`Team Code` == 392 | `Team Code` == 8 | `Team Code` == 518 | `Team Code` == 147 | `Team Code` == 365 | `Team Code` == 522) %>%
  inner_join(teams2013, by="Team Code") %>%
  ggplot(aes(x=reorder(factor(Name), Yards), y=Yards, color=Name)) +
    geom_violin() +
    labs(x="",
         y="Rushing Yards",
         title = "Distribution of Rushing Yards per Attempt by Top Football Schools") +
    theme(legend.position = "none")

# See the distribution of passing yards per attempt by top football schools
passing2013 %>%
  inner_join(teams2013, by="Team Code") %>%
  filter(`Team Code` == 392 | `Team Code` == 8 | `Team Code` == 518 | `Team Code` == 147 | `Team Code` == 365 | `Team Code` == 522) %>%
  ggplot(aes(x=reorder(factor(Name), Yards), y=Yards, color=Name)) + 
  labs(x="",
       y="Passing Yards",
       title = "Distribution of Passing Yards per Attempt by Top Football Schools") + 
  geom_violin() + 
  theme(legend.position="none")

# See total wins for each team, seperated by confrence
seasonWins2013 %>%
  inner_join(teams2013, by="Team Code") %>%
  inner_join(confrence2013, by="Conference Code") %>%
  filter(Subdivision=="FBS") %>%
  ggplot(aes(x=reorder(factor(Name.x), Wins), y=Wins, color=Name.y)) +
  geom_point() +
  labs(x="Team") +
  theme(axis.text.x=element_blank())


# I added a reorder to the above plot, I'm not sure if it helps or not, I just couldn't come to any conclusions from the graph before.
```

# What variable influences wins the most?

## Test variables:


### Yards For

```{r yardsFor}
teamGameStats2013 <- teamGameStats2013 %>%
  mutate(yardsFor=`Rush Yard`+`Pass Yard`+`Kickoff Ret Yard`+`Punt Ret Yard`+`Misc Ret Yard`+`Int Ret Yard`+`Fum Ret Yard`)

teamGameStats2013 %>%
  ggplot(aes(x=win, y=yardsFor)) + 
  geom_violin()
```


### Yards Against

```{r yardsAgainst}
findYards <- function(gameCode, teamCode){
  opponentYards <- teamGameStats2013 %>%
    filter(`Game Code` == gameCode & `Team Code` != teamCode) %>%
    select(`Rush Yard`,`Pass Yard`,`Kickoff Ret Yard`,`Punt Ret Yard`,`Misc Ret Yard`,`Int Ret Yard`,`Fum Ret Yard`)
  as.double(opponentYards[1,1]+opponentYards[1,2]+opponentYards[1,3]+opponentYards[1,4]+opponentYards[1,5]+opponentYards[1,6]+opponentYards[1,7])
}

for(i in 1:nrow(teamGameStats2013)){
  teamGameStats2013[i,72] = findYards(as.character(teamGameStats2013[i,2]), as.double(teamGameStats2013[i,1]))
}

names(teamGameStats2013)[72] <- "yardsAgainst"

teamGameStats2013 %>%
  ggplot(aes(x=win, y=yardsAgainst)) + 
  geom_violin()  +
  labs()
```

### Turnovers

```{r turnovers}
#teamGameStats2013 %>%
#  setNames(make.names(names(.), unique = TRUE))

# I had to run the data.frame through make.names for some reason, really don't know why

# But that doesn't change the dataframe right? I ran it without and it was fine  


findTurnovers <- function(gameCode, teamCode){
  opponentTurnovers <- teamGameStats2013 %>%
    setNames(make.names(names(.), unique = TRUE)) %>%
    filter(Game.Code == gameCode & Team.Code != teamCode) %>%
    select(Pass.Int, Fumble.Lost, Punt)
  as.double(opponentTurnovers[1,1] + opponentTurnovers[1,2], + opponentTurnovers[1,3])
}

for(i in 1:nrow(teamGameStats2013)){
  teamGameStats2013[i,73] = (teamGameStats2013[i, 45] + teamGameStats2013[i, 10] + teamGameStats2013[i, 37]) - findTurnovers(as.character(teamGameStats2013[i,2]), as.double(teamGameStats2013[i,1]))
}

names(teamGameStats2013)[73] <- "turnoverDiff"

teamGameStats2013 %>%
  ggplot(aes(x=win, y=turnoverDiff)) + 
  geom_violin() +
  labs(x="Win",
       y="Turnover Differential",
       title="Turnover Differential Distribution by Game Result")
```



### Home Field Advantage

```{r homeFieldAdvantage}
teamGameStats2013 %>%
  inner_join(games2013, by="Game Code") %>%
  mutate(home=(`Team Code` == `Home Team Code` & Site=="TEAM")) %>%
  group_by(home, win) %>%
  summarize(count=n()) %>%
  ggplot(aes(x=win, y=count, fill=home)) + 
  geom_bar(stat="identity", position=position_dodge()) + 
  scale_x_discrete(label=c("Lose", "Win")) +
  scale_fill_discrete(labels=c("Away", "Home")) +
  theme(legend.title=element_blank()) +
  labs(x="",
       y="Games",
       title="Home and Away vs Wins and Losses")
```



### First Downs

```{r firstDowns}
teamGameStats2013 %>%
  ggplot(aes(x=win, y=(`1st Down Rush` + `1st Down Pass` + `1st Down Penalty`))) + 
  geom_violin() +
  labs(x="Win",
       y="Total First Downs",
       title="Total First Down Distribution by Game Result")
```



### Time of Possesion Differential

```{r timeOfPossession}
findTOP <- function(gameCode, teamCode){
  opponentTOP <- teamGameStats2013 %>%
    setNames(make.names(names(.), unique = TRUE)) %>%
    filter(Game.Code == gameCode & Team.Code != teamCode) %>%
    select(Time.Of.Possession)
  as.double(opponentTOP[1,1])
}

for(i in 1:nrow(teamGameStats2013)){
  teamGameStats2013[i,74] = teamGameStats2013[i, 59] - findTOP(as.character(teamGameStats2013[i,2]), as.double(teamGameStats2013[i,1]))
}

names(teamGameStats2013)[74] <- "timeOfPossesionDifferential"

teamGameStats2013 %>%
  ggplot(aes(x=win, y=timeOfPossesionDifferential)) + 
  geom_violin() +
  labs(x="Win",
       y="Time of Possession Differential",
       title="Time of Possession Differential Distribution by Game Result")
```



### Penalties

```{r penalties}
teamGameStats2013 %>%
  inner_join(teams2013, by="Team Code") %>%
  inner_join(confrence2013, by="Conference Code") %>%
  ggplot(aes(x=win, y=Penalty)) + geom_violin()
```

